enum API_STATUS {
    SUCCESS = 'SUCCESS',
    FAILURE = 'FAILURE',
    ERROR = 'ERROR',
  }
  
  enum CAMERA_TYPE {
    PHOTO = "PHOTO",
    VIDEO = "VIDEO"
  }
  
  enum STATUS_TYPE {
    ACTIVE = "ACTIVE",
    ARCHIVE = "ARCHIVE"
  }
  
  enum MEMBERS_FOR {
    CHANNEL = "CHANNEL",
    PROJECT = "PROJECT"
  }
  
  enum CHANNEL_ACCESS_TYPE {
    ACTIVE = "ACTIVE",
    ARCHIVED = "ARCHIVED"
  }
  
  enum MESSAGE_TYPE {
    GENERAL = "GENERAL",
    JOINED = "JOINED",
    LEAVE = "LEAVE",
  }
  
  enum CHANNEL_KIND {
    "DM" = "dm",
    "CHANNEL" = "channel",
  }
  
  enum THIRD_PARTY_SYNC {
    UPDATE_IMPORT_PROGRESS = "UPDATE_IMPORT_PROGRESS",
    IMPORT_COMPLETE = "IMPORT_COMPLETE",
    IMPORT_ERROR = "IMPORT_ERROR",
  };
  
  enum EVENT_KIND {
    MESSAGE = "MESSAGE",
    CONNECT = "connect",
    CONNECT_ERROR = "connect_error",
    JOIN = "JOIN",
    JOIN_WORKSPACE = "JOIN_WORKSPACE",
    LEAVE_WORKSPACE = "LEAVE_WORKSPACE",
    JOIN_COMPANY = "JOIN_COMPANY",
    TASK_AUTOMATION_COMPLETE = "TASK_AUTOMATION_COMPLETE",
    LEAVE = "LEAVE",
    ERROR = "ERROR",
    INIT_CHAT = "INIT_CHAT",
    ADD_REACTION = "ADD_REACTION",
    REMOVE_REACTION = "REMOVE_REACTION",
    DELETE_MESSAGE = "DELETE_MESSAGE",
    EDIT_MESSAGE = "EDIT_MESSAGE",
    DELETE_ATTACHMENT = "DELETE_ATTACHMENT",
    CLEAR_UNREAD_COUNT = "CLEAR_UNREAD_COUNT",
    JOIN_PUBLIC_CHANNEL = "JOIN_PUBLIC_CHANNEL",
    FORWARD_MESSAGE = "FORWARD_MESSAGE",
    INVITE_TO_DM = "INVITE_TO_DM",
    DELETE_CHANNEL = "DELETE_CHANNEL",
    UPDATE_CHANNEL = "UPDATE_CHANNEL",
    MEMBER_LEFT = "MEMBER_LEFT",
    NOTIFICATION = "NOTIFICATION",
    PIN_MESSAGE = "PIN_MESSAGE",
    UNPIN_MESSAGE = "UNPIN_MESSAGE",
    ADD_WORKSPACE = "ADD_WORKSPACE",
    INVITE_WORKSPACE = "INVITE_WORKSPACE",
    DELETE_WORKSPACE = "DELETE_WORKSPACE",
    UPDATE_WORKSPACE = "UPDATE_WORKSPACE",
    UPDATE_WORKSPACE_ROLE = "UPDATE_WORKSPACE_ROLE",
    ADD_PROJECT = "ADD_PROJECT",
    UPDATE_PROJECT = "UPDATE_PROJECT",
    DELETE_PROJECT = "DELETE_PROJECT",
    UPDATE_PROJECT_MEMBERS = "UPDATE_PROJECT_MEMBERS",
    UPDATE_PROJECT_COLOR = "UPDATE_PROJECT_COLOR",
    UPDATE_PROJECT_STATUS = "UPDATE_PROJECT_STATUS",
    USER_INBOX_MENTIONED = "USER_INBOX_MENTIONED",
    USER_TASK_ASSIGNED = "USER_TASK_ASSIGNED",
    TYPING_START = "TYPING_START",
    TYPING_STOP = "TYPING_STOP",
    MESSAGE_CONVERT_TO_TASK = "MESSAGE_CONVERT_TO_TASK",
    CHANNEL_TASK_UPDATE = "CHANNEL_TASK_UPDATE",
    MEMBER_DEACTIVATED = "MEMBER_DEACTIVATED",
    PLAN_UPGRADE = "PLAN_UPGRADE",
    MEMBER_DELETED = "MEMBER_DELETED",
    MEMBER_INVITE_ACCEPTED = "MEMBER_INVITE_ACCEPTED",
    MEMBER_INVITE_REJECTED = "MEMBER_INVITE_REJECTED",
    TRIAL_PLAN_SUBSCRIBE = "TRIAL_PLAN_SUBSCRIBE",
    WORKSPACE_OWNER_CHANGE = "WORKSPACE_OWNER_CHANGE",
    WORKSPACE_PUBLIC_PRIVATE_CHANGE = "WORKSPACE_PUBLIC_PRIVATE_CHANGE",
    WORKSPACE_UPDATE_CHANGE = "WORKSPACE_UPDATE_CHANGE",
    WORKSPACE_DELETE = "WORKSPACE_DELETE",
    MEMBER_INVITED_RECEIVED = "MEMBER_INVITED_RECEIVED",
    PROJECT_OWNER_CHANGE = "PROJECT_OWNER_CHANGE",
    PROJECT_MEMBER_OWNER_CHANGE = "PROJECT_MEMBER_OWNER_CHANGE",
  };
  
  enum TASK_STATUS {
    OPEN = "Open",
    TO_DO = "To Do",
    IN_PROGRESS = "In Progress",
    BLOCKED = "Blocked",
    CANCELED = "Canceled",
    DONE = "Done",
  }
  
  enum TASK_TYPE {
    TASK = "Task",
    PERSONAL = "Personal",
    SUB_TASK = "Subtask",
    MILESTONE = "Milestone",
    Epic = "Epic",
    Enhancement = "Enhancement",
    Bug = "Bug",
    Feature = "Feature",
  
  }
  
  enum Cover_IMAGE_TYPE {
    GALLERY = "GALLERY",
    UNSPLASH = "UNSPLASH",
  }
  export {
    API_STATUS,
    CAMERA_TYPE,
    THIRD_PARTY_SYNC,
    MESSAGE_TYPE,
    CHANNEL_KIND,
    EVENT_KIND,
    CHANNEL_ACCESS_TYPE,
    STATUS_TYPE,
    TASK_STATUS,
    TASK_TYPE,
    MEMBERS_FOR,
    Cover_IMAGE_TYPE,
  };